"""initial_schema_users_cyclones_observations

Revision ID: f44a20af6a89
Revises: 
Create Date: 2026-09-25 11:30:59.474812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44a20af6a89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyclones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('basin', sa.String(length=50), nullable=False),
    sa.Column('international_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('genesis_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dissipation_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('international_id')
    )
    with op.batch_alter_table('cyclones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cyclones_basin'), ['basin'], unique=False)
        batch_op.create_index(batch_op.f('ix_cyclones_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cyclones_name'), ['name'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('architecture', sa.String(length=100), nullable=False),
    sa.Column('weights_path', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metrics_manifest', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cyclone_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target_region', sa.String(length=100), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cyclone_id'], ['cyclones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_cyclone_id'), ['cyclone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_id'), ['id'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cyclone_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('observation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cyclone_id'], ['cyclones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_cyclone_id'), ['cyclone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_observation_time'), ['observation_time'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cyclone_id', sa.String(length=36), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=True),
    sa.Column('prediction_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estimated_vmax_knots', sa.Float(), nullable=True),
    sa.Column('estimated_mslp_hpa', sa.Float(), nullable=True),
    sa.Column('ri_probability_24h', sa.Float(), nullable=True),
    sa.Column('ri_risk_level', sa.String(length=30), nullable=True),
    sa.Column('explanation_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cyclone_id'], ['cyclones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_cyclone_id'), ['cyclone_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_prediction_time'), ['prediction_time'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_prediction_time'))
        batch_op.drop_index(batch_op.f('ix_predictions_id'))
        batch_op.drop_index(batch_op.f('ix_predictions_cyclone_id'))

    op.drop_table('predictions')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_observation_time'))
        batch_op.drop_index(batch_op.f('ix_observations_id'))
        batch_op.drop_index(batch_op.f('ix_observations_cyclone_id'))

    op.drop_table('observations')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_cyclone_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('cyclones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cyclones_name'))
        batch_op.drop_index(batch_op.f('ix_cyclones_id'))
        batch_op.drop_index(batch_op.f('ix_cyclones_basin'))

    op.drop_table('cyclones')
    # ### end Alembic commands ###
