"""
NOAA ADT-HURSAT Source Adapter for CycloneGuard.
Handles objective satellite intensity reanalysis data generated by the Advanced Dvorak Technique (ADT).
Scientific Note: ADT estimates are objective satellite-derived intensity proxies (T-numbers, CI-numbers)
and must NOT be conflated with direct in-situ aircraft reconnaissance or official agency best-track ground truth.
"""

from datetime import datetime
import os
from typing import Any, Dict, List, Optional

from ml.data.adapters.base import BaseDataSourceAdapter
from ml.data.schemas.adapter_results import (
    DiscoveredResource,
    DownloadResult,
    DownloadStatus,
    NormalizedData,
    ParsedData,
    ValidationCheck,
    ValidationReport,
    ValidationSeverity,
)


class ADTHursatAdapter(BaseDataSourceAdapter):
    """Adapter for NOAA ADT-HURSAT objective intensity reanalysis dataset (1978–2024)."""

    def __init__(self):
        super().__init__("noaa_adt_hursat")

    def discover(self, filters: Optional[Dict[str, Any]] = None) -> List[DiscoveredResource]:
        return [
            DiscoveredResource(
                resource_id="adt_hursat_nodd_s3",
                source_id=self.source_id,
                name="NOAA ADT-HURSAT Climate Data Record v01 (NODD Cloud)",
                remote_url="s3://noaa-gestationary-hursat/ (NOAA Open Data Dissemination)",
                time_coverage="1978-2024",
                spatial_coverage="Global Tropical Cyclones",
                format="NetCDF-4",
                metadata={
                    "parameters": [
                        "raw_t_number",
                        "final_t_number",
                        "current_intensity_ci",
                        "estimated_mslp_hpa",
                        "estimated_vmax_kts",
                        "eye_temp_c",
                        "cloud_temp_c",
                        "scene_type",
                    ],
                    "nature": "objective_intensity_proxy",
                },
            )
        ]

    def download(self, resource_id: str, target_dir: str) -> DownloadResult:
        return DownloadResult(
            source_id=self.source_id,
            resource_id=resource_id,
            status=DownloadStatus.NOT_IMPLEMENTED,
            message="Automatic ingestion not implemented: ADT-HURSAT bulk retrieval requires NOAA NODD S3 credentials or bulk downloader notebook execution.",
        )

    def validate(self, file_path: str) -> ValidationReport:
        report = ValidationReport(source_id=self.source_id, file_path=file_path, status=ValidationSeverity.VALID)
        if not os.path.exists(file_path):
            report.status = ValidationSeverity.ERROR
            report.checks.append(ValidationCheck(
                check_name="file_exists",
                passed=False,
                severity=ValidationSeverity.ERROR,
                message=f"ADT-HURSAT file not found: {file_path}",
            ))
            report.summary = "File does not exist."
            return report

        report.checks.append(ValidationCheck(
            check_name="file_exists",
            passed=True,
            severity=ValidationSeverity.VALID,
            message="File exists.",
        ))
        report.summary = "ADT-HURSAT file check complete."
        return report

    def parse(self, file_path: str) -> ParsedData:
        """Staged parser for ADT-HURSAT NetCDF files."""
        return ParsedData(
            source_id=self.source_id,
            file_path=file_path,
            records_count=0,
            raw_variables=["raw_t", "ci_num", "vmax_kts", "mslp_mb", "scene_type"],
            raw_dimensions={},
            data_payload={},
        )

    def normalize(self, parsed_data: ParsedData) -> NormalizedData:
        """Normalizes ADT proxy intensity variables."""
        return NormalizedData(
            source_id=self.source_id,
            normalized_type="adt_intensity_proxy",
            records_count=parsed_data.records_count,
            data_payload=parsed_data.data_payload,
            units={
                "raw_t": "Dvorak T-number [1.0..8.5]",
                "current_intensity_ci": "Dvorak CI-number [1.0..8.5]",
                "estimated_vmax_kts": "knots (satellite proxy estimate)",
                "estimated_mslp_hpa": "hPa / millibars",
            },
            normalization_log=["ADT intensity proxies must be tagged as algorithmic estimates, not in-situ ground truth."],
        )
